The Bassed Pro Shop
magicksRampage/endless-war pull request #35
Opened 2019-08-09 04:54 UTC by miller199

2019-08-09 23:13 UTC, magicksRampage requested changes
there's a lot here that seems questionable. I haven't gotten through all of the code yet. please do some more testing to make sure the features work as intended.

2019-08-09 23:13 UTC, magicksRampage commented on client.py
> +debug = True
turn debug mode off

2019-08-09 23:13 UTC, magicksRampage commented on client.py
> +if debug == False:
this makes no sense

2019-08-09 23:13 UTC, magicksRampage commented on ewcfg.py
> +cmd_take = cmd_prefix + 'take'
enter, store and take are too generic as commands. please rename them something more specific to fishing

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +			)
you're not doing anything with this data

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +				if item.item_type == ewcfg.it_food and item.item_props["acquisition"] != ewcfg.acquisition_fishing:
why not? lol

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +				fun = 7
change debug values back

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +				elif fisher.rod_type == "stickpole":
are you supposed to never get a bite with this rod?

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +					user_data.persist()
add a message to the pier channel and to the sewers to explain the cause of death to the players

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +				fisher.slime_type = "fresh"
please use the constants in ewcfg for the slime types

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +					size = ewcfg.fish_map[fisher.current_fish].size
shouldn't we be using fisher.current_size here?

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +				response = "You reel in a {fish}! {flavor} You grab hold and wring {slime} slime from it. also its {size}"\
probably rework this flavor text

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +	size_int = int(size_int*10000)/10000
why is it called size_int if it's generally not an integer?

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +						mixtapes.remove(item)
the item_list is assigned by reference. you're permanently removing items from the global item list here

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
> +					if result.ingredients == fish.item_props.get('id_item') or result.ingredients == "generic" and result.acquisition == ewcfg.acquisition_bartering:  # Generic means that it can be made with any fi
shouldn't it be 'id_fish'?

2019-08-09 23:13 UTC, magicksRampage commented on ewfish.py
>  				else:
there is no if to this else

2019-08-10 00:13 UTC, magicksRampage commented
also provide a feature summary please

2019-08-16 19:06 UTC, miller199 commented
once school settles down a bit ill come back to work on this.

2019-08-16 19:06 UTC, closed without merging