Scalps & spelling
magicksRampage/endless-war pull request #41
Opened 2019-08-24 14:39 UTC by miller199

Scalps are a cosmetic you get when you kill a player. Also there were some typos in nobite_text that Schrafft fixed.

2019-08-25 00:16 UTC, TrackpadSnake commented on ewcfg.py
> +    	"Still better than Minesweeper...",
please remove this one, it makes me sad

2019-08-25 01:48 UTC, miller199 commented on ewcfg.py
> +    	"Still better than Minesweeper...",
never

2019-08-28 13:09 UTC, magicksRampage requested changes

2019-08-28 13:09 UTC, magicksRampage commented on ewwep.py
> +def scalp_text(id_weapon):
makes these attributes in the EwWeapon class instead

2019-08-28 23:38 UTC, magicksRampage requested changes

2019-08-28 23:38 UTC, magicksRampage commented on ewwep.py
> +					)
why is the scalp being created twice?

2019-08-28 23:38 UTC, magicksRampage commented on ewwep.py
> +            scalp_text = ""
this part is not properly formatted.

2019-08-29 12:10 UTC, merged