Slime's End Cliffs
magicksRampage/endless-war pull request #74
Opened 2019-10-04 22:50 UTC by aristotlepenguin

A new subzone on the map: shortened version is sec
command list:
!toss <item> :
    Throw an item off the cliff. Thrown items will either sink into the sea, or get eaten by sea monsters. 
    These creatures kick up slime when they chow down, so make sure to !scavenge it.
!jump
    A form of suicide.
    All your items will be discarded as though they were !tossed. However, adorned and equipped 
    weapons should not delete. You'll leave a portion of your slime on the cliff when the krakens 
    consume you.
!push <player>
    Like !jump, but for other players.
    Players can't be !pushed if they have the "Fat Chance" or "Big Bones" mutation.
    However, having "Light as a Feather" overrides both of these and makes you vulnerable to 
    pushing.
    !bully is an alternate command. 
    !push and !bully also have a dual function outside of the Cliffs.

2019-10-08 15:40 UTC, magicksRampage requested changes

2019-10-08 15:40 UTC, magicksRampage commented on ewcfg.py
> +"You grab -SLIMEOID- and give them a noogie. Just when {} thinks this is all fun and games, you throw -SLIMEOID- into the street. They have a panic attack trying to get past all the traffic and back
you can get the same result using {slimeoid} and format(slimeoid = slimeoid.name)

2019-10-08 15:40 UTC, magicksRampage commented on ewcmd.py
> +					ewitem.give_item(id_item=item_object.id_item, id_user="ocean", id_server=cmd.message.server.id)
it won't work unless you use ewcfg.poi_id_slimesea

2019-10-08 15:40 UTC, magicksRampage commented on ewcmd.py
> +	elif targetmodel.life_state == ewcfg.life_state_corpse:
kingpins also need to be immune

2019-10-08 15:40 UTC, magicksRampage commented on ewcmd.py
> +	elif user_data.life_state == ewcfg.life_state_corpse:
kingpins need to be immune to this, too

2019-10-08 15:40 UTC, magicksRampage commented on ewcmd.py
> +	member_object = server.get_member(targetmodel.id_user)
this is the same as the 'target' variable

2019-10-08 15:40 UTC, magicksRampage commented on ewcmd.py
> +		response = "You pick {} up with your thumb and index finger, and gently toss them off the cliff. Wow. That was easy.".format(target.display_name)
why doesn't all the stuff in the else case happen here?

2019-10-08 15:40 UTC, magicksRampage commented on ewcmd.py
> +		if item_obj.soulbound == True:
also make it so you can't toss your weapon, if you're married to it

2019-10-08 15:40 UTC, magicksRampage commented on ewcmd.py
> +		slimetotal = 10000 + random.randrange(50000)
this is way too much slime for a single item. people will be dumping glasses of water from the speakeasy here en masse

2019-10-10 18:46 UTC, aristotlepenguin commented on ewcmd.py
> +					ewitem.give_item(id_item=item_object.id_item, id_user="ocean", id_server=cmd.message.server.id)
sorry about that, was using a different id before miller made slimesea fishing a thing

2019-10-15 23:18 UTC, merged