Slimernalia2019
magicksRampage/endless-war pull request #97
Opened 2019-12-16 23:31 UTC by MeatyLearner

Just like last year's Slimernalia:

- Food is free

- Roles have been reversed: only juveniles can kill

- You can gamble from anywhere, however...

New this Slimernalia:

- You can buy a Gellphone from the Bazaar, which allows you to gamble from anywhere while you're using it.

- You can now gamble slime! Just add "slime" to the end of the commands you would usually do.

- You can buy wrapping paper at Glocksbury Comics, which you can use to !wrap gifts for other players. They can then !unwrap your gift.

- You may now have slimeoid battles anywhere AND bet slime on them.

- Killing players gives you their sigillaria, a furniture item, instead of their scalp.

- A new cosmetic item, the pileus, has been added to the Bazaar.

- The Slime Casino has been acquired by SlimeCorp, and has been rebranded the SlimeCorp Casino. SlimeCorp takes 20% of all your winnings.

The Kingpin of Slimernalia

- A new leaderboard has been added: Most Festive. Whoever is at the top of this leaderboard becomes the Kingpin of Slimernalia for that day.

- Use !festivity to check your current festivity.

Your festivity increases by doing the following:

- Killing players (1 festivity per slime splattered on districts)

- Wrapping, unwrapping and giving gifts (100 festivity for wrapping and unwrapping, 1000 for giving)

- Gambling (1 festivity per slime gambled, 1 festivity per 1,000,000,000,000 SlimeCoin gambled)

- Eating food (1 festivity per point of hunger restored)

- Owning sigillaria (100 festivity for each sigillaria in your inventory)

**!yoslimernalia**

2019-12-16 23:35 UTC, MeatyLearner commented
for k1p's eyes only:
-fixed a bug where renameable items could be used instead of the expected item (ie: !makecostume costumekit to make recursive costumekit costumes)
-garrote works again
-fixed bugs regarding permissions from the subzone removal update

2019-12-17 22:11 UTC, magicksRampage requested changes

2019-12-17 22:11 UTC, magicksRampage commented on ewcasino.py
> +	if cmd.message.channel.name != ewcfg.channel_realestateagency:
should be channel_casino

2019-12-17 22:11 UTC, magicksRampage commented on ewcmd.py
> +		if item.item_type == ewcfg.it_furniture:
gifts are created as general item types, not furniture

2019-12-17 22:11 UTC, magicksRampage commented on ewitem.py
> +						await cmd.client.add_roles(author, gellphone_role)
I really dislike this way of dealing with the gellphone role. we have all role changes unified in ewrolemgr.updateRoles() for a good reason. this kind of thing is a pain to debug and maintain

2019-12-17 22:11 UTC, magicksRampage commented on ewitem.py
> +						await cmd.client.add_roles(author, gellphone_role)
instead, give gellphones an item_prop that says whether it's on or off and check for that in updateRoles()

2019-12-17 22:11 UTC, magicksRampage commented on ewmap.py
> +	if channel_name_is_poi(cmd.message.channel.name) is False or user_poi.is_subzone:
user_poi is never a subzone. it's always the main district

2019-12-17 22:12 UTC, magicksRampage commented on ewitem.py
> +						await cmd.client.add_roles(author, gellphone_role)
the same goes for the slimernalia kingpin role actually

2019-12-17 23:42 UTC, merged